/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { NameInfo, UserStats } from '../types';
import { suggestNamesByCategory } from '../services/geminiService';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Loader2, Plus, Check, Heart } from 'lucide-react';

export default function GeneratorView({ stats, allNames, setAllNames }: { 
  stats: UserStats; 
  allNames: NameInfo[];
  setAllNames: React.Dispatch<React.SetStateAction<NameInfo[]>>;
}) {
  const [prompt, setPrompt] = useState('');
  const [results, setResults] = useState<NameInfo[]>([]);
  const [loading, setLoading] = useState(false);
  const [savedBatch, setSavedBatch] = useState<string[]>([]);

  const PRESETS = ['Nature', 'Mythological', 'Vintage 1920s', 'Bohemian', 'Royal', 'Celestial'];

  const handleGenerate = async (preset?: string) => {
    const query = preset || prompt;
    if (!query) return;

    setLoading(true);
    setResults([]);
    const names = await suggestNamesByCategory(query);
    
    // Add temporary IDs
    const formatted = names.map((n: any, i: number) => ({
      ...n,
      id: `gen-${Date.now()}-${i}`,
      meaning: 'Generated by AI Curators'
    }));

    setResults(formatted);
    setLoading(false);
  };

  const saveToMain = (name: NameInfo) => {
    if (!allNames.some(n => n.name === name.name)) {
      setAllNames(prev => [...prev, name]);
      setSavedBatch(prev => [...prev, name.id]);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 md:p-12 min-h-full bg-[#fdfaf5]">
      <div className="mb-12">
        <span className="text-[10px] font-bold text-[#8a9a5b] tracking-[0.3em] uppercase mb-4 block">THE FORGE</span>
        <h2 className="text-5xl font-serif font-bold italic tracking-tight text-[#5a5a40]">Name Generator</h2>
        <p className="text-[#998b7a] mt-4 max-w-lg font-serif italic text-lg opacity-80 leading-relaxed">
          The curators utilize our most advanced models to forge new identities based on your specific prompts.
        </p>
      </div>

      <div className="flex flex-col gap-10 mb-12">
        <div className="flex flex-col gap-4">
          <div className="relative">
            <textarea 
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. 'Modern names for a beach baby' or 'Short Nordic names'..."
              className="w-full h-32 p-8 bg-white border border-[#e0d6c8] rounded-[2.5rem] outline-none focus:ring-1 focus:ring-[#8a9a5b] focus:border-[#8a9a5b] shadow-sm transition-all font-serif italic text-lg"
            />
            <button 
              onClick={() => handleGenerate()}
              disabled={loading || !prompt}
              className="absolute bottom-4 right-4 bg-[#5a5a40] text-white px-8 py-3 rounded-full font-bold flex items-center justify-center gap-2 hover:bg-[#8a9a5b] transition-all disabled:opacity-50 shadow-lg"
            >
              {loading ? <Loader2 className="animate-spin text-white/50" size={20} /> : <Sparkles size={20} />}
              Forge
            </button>
          </div>

          <div className="flex flex-wrap gap-2">
            {PRESETS.map(preset => (
              <button 
                key={preset}
                onClick={() => handleGenerate(preset)}
                className="px-4 py-1.5 bg-[#f4eee6] hover:bg-[#e8e0d4] text-[#3d3d3d] border border-[#e0d6c8] rounded-full text-[10px] font-bold uppercase tracking-widest transition-all"
              >
                {preset}
              </button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <AnimatePresence>
            {results.map((name) => (
              <motion.div 
                key={name.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                className="bg-white border border-[#e0d6c8] p-6 rounded-[2rem] flex items-center justify-between group hover:border-[#8a9a5b] transition-all shadow-sm"
              >
                <div>
                  <h3 className="text-3xl font-serif font-bold text-[#5a5a40] italic grow-0 group-hover:scale-105 transition-transform origin-left">{name.name}</h3>
                  <p className="text-[10px] text-[#998b7a] font-bold uppercase tracking-widest mt-1">{name.origin} • {name.gender}</p>
                </div>
                <button 
                  onClick={() => saveToMain(name)}
                  disabled={savedBatch.includes(name.id)}
                  className={`p-4 rounded-2xl transition-all shadow-sm ${
                    savedBatch.includes(name.id) 
                      ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' 
                      : 'bg-[#fdfaf5] text-[#8a9a5b] hover:bg-[#8a9a5b] hover:text-white border border-[#e0d6c8]'
                  }`}
                >
                  {savedBatch.includes(name.id) ? <Check size={20} /> : <Plus size={20} />}
                </button>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>

        {results.length === 0 && !loading && (
          <div className="py-24 flex flex-col items-center justify-center text-center opacity-30 border-2 border-dashed border-[#e0d6c8] rounded-[3rem] bg-white/40">
            <Sparkles size={48} className="mb-4 text-[#8a9a5b]" />
            <p className="font-serif italic text-xl text-[#998b7a]">Enter a vibe to start the forge engine.</p>
          </div>
        )}
      </div>
    </div>
  );
}
